### ISSUE TITLE
Pretrained model for stage II?

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-codeformer#5]
Seeing that https://github.com/sczhou/CodeFormer/commits/master got a pretrained model for stage II (on Jul 23, 2023), I was wondering whether this could be added here too. :)

Btw. the filter is really useful during upscaling decent dvd content when running some denoising after it to remove some of the artifacts it sometimes produces.

**Comment by HolyWu** [comment]
That's for training purpose, not for inference.

**Comment by Selur** [comment]
Ah okay, thanks.
